### ISSUE TITLE
storage path documentation

### ISSUE THREAD

**Issue by coldshivery** [matjaz/presence-tracker#1]
"Storage persists custom device data." is all the documentation currently. I am trying to get Homey to work with the presence-tracker app but i have no idea where i should locate data.json, or what it is? If i simply remove it from the config.json the program still crashes.

Us users need more documentation on how to set this up properly.

Thanks and goodluck.

**Comment by matjaz** [comment]
I've added config documentation https://github.com/matjaz/presence-tracker/wiki/Config-options
Hope it answers some questions.
