### ISSUE TITLE
Aprscan

### ISSUE THREAD

**Issue by Neal-11** [matjaz/presence-tracker#28]
I keep getting a not found on the arpscan function. I've installed arp-scan, it's in my modules, added the arguments to the config, but still nothing.

{
  "presence": {
    "interval": 30000,
    "addedCount": 0,
    "removedCount": 3
  },
  "server": {
    "port": 3000,
    "logRequest": false,
    "allowedOrigins": ["http://homey.local"]
  },
  "storage": {
    "path": "data.json"
  },
  "hooks": [],
  "providers": {
    "arpscan": {
      "args": "-l -N -I wlan0"
    },

**Comment by matjaz** [comment]
You need `arp-scan` command on system where running tracker. see https://github.com/matjaz/presence-tracker/wiki/Raspberry-Pi-instructions#arp-scan

**Comment by Neal-11** [comment]
Got arp-scan installed, yes

**Comment by matjaz** [comment]
Which system are you running? Try arp-scan command in shell. On Linux it should work with default args.
