### ISSUE TITLE
can't install nodejs according to instructions on my rpi3

### ISSUE THREAD

**Issue by TheMrCaveman** [matjaz/presence-tracker#29]
See pictures 

![install 1](https://cloud.githubusercontent.com/assets/9423165/23125107/7e24aca6-f770-11e6-843f-2cbe4d40603f.jpg)
![install 2](https://cloud.githubusercontent.com/assets/9423165/23125108/815a2bf8-f770-11e6-8ce4-b6a28f556200.jpg)
![install 3](https://cloud.githubusercontent.com/assets/9423165/23125617/fad89ecc-f772-11e6-9716-6bda1d07e46a.jpg)

seems it needs to be tar -xvf since z is for gzip files!

![install 4](https://cloud.githubusercontent.com/assets/9423165/23125705/6919c442-f773-11e6-9f0e-e7da28c22e95.jpg)
![install 5](https://cloud.githubusercontent.com/assets/9423165/23125743/90c031ac-f773-11e6-8f71-533f668b938c.jpg)

And here i am stuck:(

**Comment by matjaz** [comment]
Try `cd node-v6.9.5-linux-arm64` then you can copy `bin/node` to `$PATH`.
NOTE: Haven't tested tracker with 6.9, but it should work.

**Comment by TheMrCaveman** [comment]
mm got nodejs and npm to work and installed tracker
Now we have this as a result:
![install 6](https://cloud.githubusercontent.com/assets/9423165/23139763/55850226-f7ae-11e6-89ac-7ae9df6929cd.jpg)

**Comment by matjaz** [comment]
Looks like you're missing `config.json`. See https://github.com/matjaz/presence-tracker#installation

**Comment by TheMrCaveman** [comment]
No, i had to start the tracker with sudo;)

**Comment by matjaz** [comment]
sudo should not be required https://github.com/matjaz/presence-tracker/wiki/Raspberry-Pi-instructions#troubleshooting

**Comment by TheMrCaveman** [comment]
thanks that worked, so to add new providers i have to put ip of phone in config.json right? Sorry for all the noob questions btw but i am completly new to linux;)
